### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by zombiestruck** [Pocketkid2/RegionTeleport#1]
Just simply doesn't load.

**Comment by Pocketkid2** [comment]
Can you post a log?

**Comment by Pocketkid2** [comment]
Or any other information like what plugins are loaded?

**Comment by zombiestruck** [comment]
I'll send a log shortly. Custom plugins, won't conflict.

**Comment by tomcarlson** [comment]
I had the same problem.  The plugin was not loading.

Looking at the log, I saw this.

```
$ zgrep RegionTeleport 2015-12-21-3.log.gz
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError:         
com/github/pocketkid2/regionteleport/RegionTeleportPlugin : Unsupported major.minor version 52.0
Caused by: java.lang.UnsupportedClassVersionError:  
com/github/pocketkid2/regionteleport/RegionTeleportPlugin : Unsupported major.minor version 52.0
```

On a whim, I decided to update from java openjdk-7 to openjdk-8 to see if that would address the problem.  After I did this and rebooted, the plugin is now loading.

**Comment by Pocketkid2** [comment]
Yeah I think I compiled for Java 8 with this plugin, servers should be running it anyway

**Comment by Pocketkid2** [comment]
Official Solution: Use Java 8
